Updates
firstandthird/healthcheck pull request #8
Opened 2017-05-22 20:20 UTC by dawnerd

2017-05-22 20:21 UTC, dawnerd commented
Not sure why travis is enabled when there's no travisfile

2017-05-23 16:59 UTC, jgallen23 requested changes

2017-05-23 16:59 UTC, jgallen23 commented on conf/default-routes.yaml
> +    enableCache: '{{ENV.ENABLE_CACHE}}'
I don't think we need cache for this

2017-05-23 16:59 UTC, jgallen23 commented on package.json
> +    "hapi-nunjucks-helpers": "3.1.1",
are these used?

2017-05-23 16:59 UTC, jgallen23 commented on package.json
> +    "rapptor": "1.13.0",
I think you need to change some settings to work with logr flat for this

2017-05-23 16:59 UTC, jgallen23 commented on conf/default.yaml
> +  inert:
do we need inert? doesn't seem like you are doing any static file serving

2017-05-23 16:59 UTC, jgallen23 commented on package.json
> +    "hapi-auto-handler": "1.4.1",
I don't see auto handler being used anywhere

2017-07-06 00:33 UTC, closed without merging